name: .NET

on:
  push:
    branches: 
      - "main"
      - "Development"
  pull_request:
    branches: 
      - "main"
      - "Development"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    # - name: Publish to NuGet
    #   if: github.ref == 'refs/heads/main'
    #   env:
    #     NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    #   run: dotnet nuget push '**/*.nupkg' --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json

    # - name: Deploy to server
    #   if: github.ref == 'refs/heads/main'
    #   uses: appleboy/ssh-action@v0.1.5
    #   with:
    #     host: ${{ secrets.SSH_HOST }}
    #     username: ${{ secrets.SSH_USERNAME }}
    #     key: ${{ secrets.SSH_KEY }}
    #     script: |
    #       cd /path/to/deployment
    #       git pull origin main
    #       dotnet publish -c Release
